Hotfix
enjin/platform-beam pull request #46
Opened 2023-11-15 11:06 UTC by enjinabner

2023-11-15 13:13 UTC, leonardocustodio approved these changes

2023-11-15 13:36 UTC, v16Studios requested changes

2023-11-15 13:36 UTC, v16Studios commented on lang/en/type.php
> +    'attribute.description' => 'The initial attribute for the token.',
I assume the attributes are only relevant when using mint on demand mode, so we should probably clarify here.

```suggestion
    'attribute.description' => 'An initial attribute to set for the token when minting on demand.',
```

2023-11-16 01:35 UTC, leonardocustodio approved these changes

2023-11-16 01:36 UTC, merged