[PLA-1970] Stop RemoveClaimToken from being run on Token Transferred events.
enjin/platform-beam pull request #94
Opened 2024-08-30 20:51 UTC by v16Studios

2024-08-30 20:55 UTC, leonardocustodio approved these changes

2024-09-02 13:08 UTC, enjinabner approved these changes

2024-09-02 13:50 UTC, Bradez requested changes
Proper fix required rather than a hotfix. `RemoveClaimToken` does not need to be ran for FTs in the first place. The query also needs fixing to improve the overall efficiency.

2024-09-03 09:11 UTC, closed without merging

2024-09-03 09:13 UTC, v16Studios commented
This work around is not needed, instead this [PR](https://github.com/enjin/platform-beam/pull/95) provides a more comprehensive solution.